### ISSUE TITLE
botocore error: You must specify a region

### ISSUE THREAD

**Issue by abourramouss** [CLOUDLAB-URV/dataplug#12]
I am trying to run the cities example with dataplug on the rack:

```
from dataplug.dataplug import CloudObject
from dataplug.dataplug.formats.generic.csv import CSV, partition_num_chunks


# Localhost minio config
minio = {
    # "aws_access_key_id": "rackcred",
    # "aws_secret_access_key": "rackcred",
    "endpoint_url": "rackendpoint",
    "botocore_config_kwargs": {"signature_version": "s3v4"},
    "role_arn": "arn:aws:iam::123456789012:role/S3Access",
    # "use_token": True,
}

if __name__ == "__main__":
    CSV.debug()
    # co = CloudObject.new_from_file(CSV, "../examples/sample_data/cities.csv", "s3://dataplug/cities.csv",
    #                                s3_config=minio, override=True)
    #
    # parallel_config = {"verbose": 10}
    # co.preprocess(parallel_config=parallel_config, debug=True)

    co = CloudObject.from_s3(CSV, "s3://test-bucket/cities.csv", s3_config=minio)

    data_slices = co.partition(partition_num_chunks, num_chunks=25)
    for ds in data_slices:
        print(ds.get_as_pandas())
        print("---")
```

The issue is:

```
{'attrs_types': {'columns': 'List[str]', 'dtypes': 'List[str]'},
 'co_class': <class 'dataplug.dataplug.formats.generic.csv.CSV'>,
 'default_attrs': {},
 'finalizer_function': None,
 'preprocessing_function': <function preprocess_csv at 0x7ff3c945f250>}
Traceback (most recent call last):
  File "/home/users/ayman/ayman/extract-project/test.py", line 22, in <module>
    co = CloudObject.from_s3(CSV, "s3://test-bucket/cities.csv", s3_config=minio)
  File "/home/users/ayman/ayman/extract-project/dataplug/dataplug/cloudobject.py", line 120, in from_s3
    co = cls(data_format, obj_path, metadata_path, attributes_path, s3_config)
  File "/home/users/ayman/ayman/extract-project/dataplug/dataplug/cloudobject.py", line 59, in __init__
    self._s3: S3Client = PickleableS3ClientProxy(**storage_config)
  File "/home/users/ayman/ayman/extract-project/dataplug/dataplug/storage/picklableS3.py", line 81, in __init__
    response = sts_admin.assume_role(
  File "/home/users/ayman/.local/lib/python3.10/site-packages/botocore/client.py", line 553, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/users/ayman/.local/lib/python3.10/site-packages/botocore/client.py", line 989, in _make_api_call
    http, parsed_response = self._make_request(
  File "/home/users/ayman/.local/lib/python3.10/site-packages/botocore/client.py", line 1015, in _make_request
    return self._endpoint.make_request(operation_model, request_dict)
  File "/home/users/ayman/.local/lib/python3.10/site-packages/botocore/endpoint.py", line 119, in make_request
    return self._send_request(request_dict, operation_model)
  File "/home/users/ayman/.local/lib/python3.10/site-packages/botocore/endpoint.py", line 198, in _send_request
    request = self.create_request(request_dict, operation_model)
  File "/home/users/ayman/.local/lib/python3.10/site-packages/botocore/endpoint.py", line 134, in create_request
    self._event_emitter.emit(
  File "/home/users/ayman/.local/lib/python3.10/site-packages/botocore/hooks.py", line 412, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
  File "/home/users/ayman/.local/lib/python3.10/site-packages/botocore/hooks.py", line 256, in emit
    return self._emit(event_name, kwargs)
  File "/home/users/ayman/.local/lib/python3.10/site-packages/botocore/hooks.py", line 239, in _emit
    response = handler(**kwargs)
  File "/home/users/ayman/.local/lib/python3.10/site-packages/botocore/signers.py", line 105, in handler
    return self.sign(operation_name, request)
  File "/home/users/ayman/.local/lib/python3.10/site-packages/botocore/signers.py", line 186, in sign
    auth = self.get_auth_instance(**kwargs)
  File "/home/users/ayman/.local/lib/python3.10/site-packages/botocore/signers.py", line 305, in get_auth_instance
    raise botocore.exceptions.NoRegionError()
botocore.exceptions.NoRegionError: You must specify a region.
```

Do we need to specify a region for the botoclient to interact with the rack endpoint?
When passing the region:

`botocore.exceptions.NoCredentialsError: Unable to locate credentials`

**Comment by aitorarjona** [comment]
can you format the traceback correctly? otherwise it's impossible to see anything

**Comment by abourramouss** [comment]
> can you format the traceback correctly? otherwise it's impossible to see anything

Yes, sorry!

**Comment by aitorarjona** [comment]
The storage backend relies on boto3 to load the credentials in a secure way:  https://boto3.amazonaws.com/v1/documentation/api/latest/guide/credentials.html
If you are using minio, you must then specfy the region, but still configure boto3 with your minio credentials, including region.

**Comment by aitorarjona** [comment]
No, dataplug creates it's own client, becuase it implements logic to create temporary credentials and to enable pickling of an authenticated client.

**Comment by abourramouss** [comment]
I understand now, thank you very much!

**Comment by abourramouss** [comment]
The only question remaining is the region parameter, does it make sense if I am accessing an endpoint under a cluster? It makes sense for aws, but for a remote cluster?

**Comment by aitorarjona** [comment]
I think region is a required parameter for accessing S3 using boto3, but minio ignores the region, you can use "us-east-1", for instance, but it makes no effect.
